source "https://rubygems.org"
gem "jekyll", "~> 4.1.1"
gem "just-the-docs"
gem "jekyll-redirect-from"
group :jekyll_plugins do
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

