name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: gradle test jacocoTestReport
        run: ./gradlew test jacocoTestReport
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: build/reports/tests/test
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html
      - name: gradle connectedAndroidTest
        uses: vgaidarji/android-github-actions/emulator@v1.0.0
        env:
          JAVA_HOME:
      - name: chmod output
        run: chmod -R $(whoami) .
      - name: Generate integration code coverage report
        run: ./gradlew jacocoIntegrationTestReport
      - name: Save integration test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: integration-test-result
          path: build/reports/tests/integrationTest
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: integration-test-coverage
          path: build/reports/jacoco/jacocoIntegrationTestReport/html
      - name: deploy-snapshot
        run: .buildsystem/deploy-github.sh
        env:
          GITHUB_MAVEN_USERNAME: ${{ secrets.GITHUB_MAVEN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}